all:
    # install pycocotools locally
	/home/mingtao.huang/anaconda3/envs/TF/bin/python3 setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	/home/mingtao.huang/anaconda3/envs/TF/bin/python3 setup.py build_ext install
	rm -rf build
